const jCategory = [
    {
        index: 0,
        image: "https://th.bing.com/th/id/OIP.uBYsSL7JDekYP3VpxWZvYQHaHa?rs=1&pid=ImgDetMain",
        title: "Web Developer",
        rate:'$1200-1500/m',
        av:"Full Time",
        companyName:"Google",
        location:"Germany",
        vacancy:"01",
        hours:"50 hr / Week",
        description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more or less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose(injected humour and the like).",
        workplace:"Work from home",
        education: "Bachelor degree in any Computer Science Course",
        experience: "2 to 5 year(s)",
    },
    {
        index: 1,
        image: "https://th.bing.com/th/id/OIP.Z0WaAEp4fOq3Q92Idq29cwHaHa?rs=1&pid=ImgDetMain",
        title: "Freelancer",
        rate:'$900-1200/m',
        av:"Freelancer",
        companyName:"Uber",
        location:"USA",
        vacancy:"04",
        hours:"40 hr / Week",
        description:"Join Uber as a Driver Partner and earn money on your schedule. Use the Uber app to connect with riders, offering safe and reliable transportation. As a driver, you'll have the flexibility to choose your working hours, access in-app navigation, and earn competitive fares. Provide excellent customer service and maintain a clean and well-maintained vehicle to enhance the rider experience. Safely transport passengers to their destinations. Use the Uber app for navigation and trip management. Provide professional and friendly service. Maintain a clean, roadworthy vehicle.",
        workplace:"Work from office",
        education:"Degree in any Computer Science Course",
        experience:"1 to 5 year(s)",

    },
    {
        index: 2,
        image: "https://th.bing.com/th/id/OIP.CH_Ljw5hpxU03HXEuOC1pAHaHa?rs=1&pid=ImgDetMain",
        title: "Business Associate",
        rate:'$900-1100/m',
        av:"Part Time",
        companyName:"Linkedin",
        location:"Liberia",
        vacancy:"02",
        hours:"35 hr / Week",
        description:"We are seeking a LinkedIn App Specialist to enhance our presence and engagement on the LinkedIn platform. The ideal candidate will manage LinkedIn app functions, optimize user experiences, and implement strategies for professional networking success. Manage and update the LinkedIn app for professional branding and networking. Create and post engaging content to drive connections and interactions. Analyze user activity and engagement metrics to improve performance. Stay updated with LinkedIn’s features and trends to maximize platform potential. Identify and connect with key industry professionals and groups.",
        workplace:"Work from office",
        education:"Bachelor degree in any Computer Science Course",
        experience:"2 to 4 year(s)",
    },
    {
        index: 3,
        image: "https://th.bing.com/th/id/OIP.ENIq-U2iyx2c51zh5Hv5aAAAAA?rs=1&pid=ImgDetMain",
        title: "Digital Marketing",
        rate:'$1200-1500/m',
        av:"Full Time",
        companyName:"Facebook",
        location:"France",
        vacancy:"05",
        hours:"55 hr / Week",
        description:"Facebook is a leading social media platform that enables users to connect, share, and engage with friends, family, and communities worldwide. It allows users to create profiles, post updates, share photos and videos, join groups, participate in events, and discover content tailored to their interests. Stay updated with posts and stories from friends and pages you follow. Instant messaging and video calling functionality. Engage in discussions, share resources, and collaborate on shared interests. Share short videos and temporary posts to connect with your audience. Buy and sell items locally.",
        workplace:"Work from home",
        education:"Degree in any Computer Science Course",
        experience:"3 to 6 year(s)",
    },
    {
        index: 4,
        image: "https://th.bing.com/th/id/OIP.F1OYoVYfPQwhP3PhNu8wnwHaHa?rs=1&pid=ImgDetMain",
        title: "User Experience",
        rate:'$1100-1300/m',
        av:"Part Time",
        companyName:"Yahoo!",
        location:"Yemen",
        vacancy:"02",
        hours:"47 hr / Week",
        description:"We are seeking a skilled Mobile App Developer to join our team at Yahoo and contribute to creating innovative, user-friendly applications that enhance the digital experience for millions of users worldwide.Collaborate with product managers, designers, and engineers to implement features and optimize app performance.Stay updated with industry trends and incorporate emerging technologies into app development. Design, develop, and maintain Yahoo's mobile applications for iOS and Android platforms. Monitor app performance, debug issues, and ensure high-quality user experiences.Write clean, maintainable, and scalable code following best practices.",
        workplace:"Work from office",
        education:"Bachelor degree in any Computer Science Course",
        experience:"1 to 2 year(s)",
    },
    {
        index: 5,
        image: "https://th.bing.com/th/id/OIP.xa0FgRBsvMi7bmVNCDYsCgHaHa?rs=1&pid=ImgDetMain",
        title: "Online Marketing",
        rate:'$900-1200/m',
        av:"Full Time",
        companyName:"Instagram",
        location:"India",
        vacancy:"03",
        hours:"60 hr / Week",
        description:"We are seeking a creative and detail-oriented individual to manage and optimize our presence on Instagram. The ideal candidate will leverage the platform's features to enhance brand visibility, engage with our audience, and drive measurable results. Create, schedule, and publish visually compelling content (posts, stories, reels). Analyze performance metrics and optimize campaigns based on insights. Collaborate with the marketing team to align Instagram strategies with broader goals. Stay updated on Instagram trends, tools, and best practice. Develop and implement strategies to increase followers and engagement.",
        workplace:"Work from home",
        education:"Bachelor degree in any Computer Science Course",
        experience:"1 to 3 year(s)",
    },
    {
        index: 6,
        image: "https://th.bing.com/th/id/OIP.zNUSFf1aeErMeOFY9s1--QHaHa?rs=1&pid=ImgDetMain",
        title: "Product Designer",
        rate:'$800-1000/m',
        av:"Freelancer",
        companyName:"Wordpress",
        location:"Washington DC",
        vacancy:"01",
        hours:"45 hr / Week",
        description:"We are seeking a skilled WordPress Developer to join our team. The ideal candidate will have expertise in designing, developing, and maintaining WordPress websites. You will collaborate with cross-functional teams to create user-friendly, responsive, and visually appealing websites that meet client requirements. Design and develop custom WordPress themes and plugins. Optimize website performance, speed, and scalability. Ensure cross-browser and mobile responsiveness. Troubleshoot and resolve website issues or bugs.Collaborate with designers and stakeholders to implement creative solutions.",
        workplace:"Work from home",
        education:"Degree in any Computer Science Course",
        experience:"2 to 3 year(s)",
    },
]